<a href="https://colab.research.google.com/github/hiiamjay/NLP/blob/main/J075_NLP_ASG_1_SPAM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys, os
#to prevent the nltk downloader to print all lines
# Disable
def blockPrint():
    sys.stdout = open(os.devnull, 'w')

# Restore
def enablePrint():
    sys.stdout = sys.__stdout__


In [2]:
import nltk
blockPrint()
nltk.download()

Downloader> all
Downloader> d
  Identifier> all
Downloader> q


True

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from string import punctuation 
from nltk.corpus import stopwords 
from nltk.tokenize import word_tokenize 
from nltk.stem import LancasterStemmer
from nltk.tag import pos_tag

from nltk.stem import WordNetLemmatizer

from string import punctuation
from nltk.corpus import stopwords

from nltk.tokenize import word_tokenize

In [ ]:
data=pd.read_csv("/content/spam (1).csv",encoding='latin-1')

In [ ]:
data=data.drop(['Unnamed: 2'	,'Unnamed: 3','Unnamed: 4'],axis=1)
data.columns = ['label', 'content']

In [ ]:
remove = list(stopwords.words('english'))+list(punctuation)
lemmatizer = WordNetLemmatizer()
lemmatizer = WordNetLemmatizer()
corpus = data['content'].tolist()
len(corpus)

5572

In [ ]:
final_corpus = []
for i in range(len(corpus)):
  word = word_tokenize(corpus[i].lower())
  word = [lemmatizer.lemmatize(y) for y in word if y not in remove]
  j = " ".join(word)
  final_corpus.append(j)

In [ ]:
final_corpus[0:5]

['go jurong point crazy.. available bugis n great world la e buffet ... cine got amore wat ...',
 'ok lar ... joking wif u oni ...',
 "free entry 2 wkly comp win fa cup final tkts 21st may 2005. text fa 87121 receive entry question std txt rate c 's apply 08452810075over18 's",
 'u dun say early hor ... u c already say ...',
 "nah n't think go usf life around though"]

In [ ]:
label_list=data['label'].tolist()
df = pd.DataFrame(final_corpus)
df['label'] = label_list
df.columns=['content','label']

In [ ]:
df.head()

content label
0  go jurong point crazy.. available bugis n grea...   ham
1                    ok lar ... joking wif u oni ...   ham
2  free entry 2 wkly comp win fa cup final tkts 2...  spam
3        u dun say early hor ... u c already say ...   ham
4            nah n't think go usf life around though   ham

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
vector = tfidf.fit_transform(df['content'])
x_train = vector.toarray()
y_train= df['label']

In [ ]:
from sklearn.naive_bayes import MultinomialNB
ab = MultinomialNB()
ab.fit(x_train,y_train)
ypred = ab.predict(x_train)

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_train,ypred))
print(confusion_matrix(y_train,ypred))
print(classification_report(y_train,ypred))

0.9834888729361091
[[4825    0]
 [  92  655]]
              precision    recall  f1-score   support

         ham       0.98      1.00      0.99      4825
        spam       1.00      0.88      0.93       747

    accuracy                           0.98      5572
   macro avg       0.99      0.94      0.96      5572
weighted avg       0.98      0.98      0.98      5572



In [ ]:
from sklearn.naive_bayes import GaussianNB
ab = GaussianNB()
ab.fit(x_train,y_train)
ypred = ab.predict(x_train)

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_train,ypred))
print(confusion_matrix(y_train,ypred))
print(classification_report(y_train,ypred))

0.9341349605168701
[[4458  367]
 [   0  747]]
              precision    recall  f1-score   support

         ham       1.00      0.92      0.96      4825
        spam       0.67      1.00      0.80       747

    accuracy                           0.93      5572
   macro avg       0.84      0.96      0.88      5572
weighted avg       0.96      0.93      0.94      5572



In [ ]:
from xgboost import XGBClassifier
model = XGBClassifier(max_depth=10,random_state=1,learning_rate=0.05,seed=1)
model.fit(x_train, y_train)
y_pred=model.predict(x_train)

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_train,ypred))
print(confusion_matrix(y_train,ypred))
print(classification_report(y_train,ypred))

0.9341349605168701
[[4458  367]
 [   0  747]]
              precision    recall  f1-score   support

         ham       1.00      0.92      0.96      4825
        spam       0.67      1.00      0.80       747

    accuracy                           0.93      5572
   macro avg       0.84      0.96      0.88      5572
weighted avg       0.96      0.93      0.94      5572

